# Generated by Django 2.1.5 on 2019-11-11 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.IntegerField(blank=True, default=0)),
                ('cat2', models.IntegerField(blank=True, default=2)),
                ('cat3', models.IntegerField(blank=True, default=4)),
                ('cat4', models.IntegerField(blank=True, default=6)),
                ('mouse', models.IntegerField(blank=True, default=59)),
                ('cat_turn', models.BooleanField(blank=True, default=True)),
                ('cat_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_cat', to=settings.AUTH_USER_MODEL)),
                ('mouse_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_mouse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATED', models.BooleanField(default=False)),
                ('ACTIVE', models.BooleanField(default=False)),
                ('FINISHED', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(blank=True, default=0)),
                ('target', models.IntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(blank=True)),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Game')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
