# Generated by Django 2.1.5 on 2019-11-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20191126_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
