# Generated by Django 2.1.5 on 2019-11-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='ACTIVE',
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='CREATED',
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='FINISHED',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat_turn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(default=59),
        ),
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='datamodel.Game'),
        ),
    ]
