# Generated by Django 2.1.5 on 2019-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20191112_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
