# Generated by Django 2.1.5 on 2019-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0009_auto_20191126_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(default=9),
        ),
    ]
