# Generated by Django 2.1.5 on 2019-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0010_auto_20191210_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(default=16),
        ),
    ]
