# Generated by Django 2.1.5 on 2019-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0011_auto_20191210_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(default=59),
        ),
    ]
