# Generated by Django 2.1.5 on 2019-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0012_auto_20191210_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='cat1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='cat2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='move',
            name='cat3',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='move',
            name='cat4',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='move',
            name='mouse',
            field=models.IntegerField(default=59),
        ),
    ]
